services:
  mysql:
    image: cms-mysql:latest
    container_name: cms-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
    ports:
      - ""
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge

volumes:
  mysql-data:
    driver: local
