services:
  mysql:
    image: my-mysql-with-data:latest
    container_name: cms-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge

volumes:
  mysql-data:
    driver: local
